### ISSUE TITLE
Nama kolom id di tabel schedule

### ISSUE THREAD

**Issue by zabilsabri** [zabilsabri/Kelompok2-Tugas-BasisData-Praktisi#13]
Nama kolom id di tabel schedule seharusnya di ubah menjadi student_id, agar lebih gampang dipahami oleh orang - orang bahwa kolom tersebut mereference ke tabel student_info.

**Comment by ztzrk** [comment]
Mungkin apabila nama kolom tidak ingin diubah bisa dilakukan dengan menambahkan alias di kolom id tabel student
